import Svg, { Path } from 'react-native-svg';

// Hanging toran: catenary string + 9 mango leaves. Exact path data and leaf
// positions copied directly from the reviewed Toran reference prototype
// (utsav-animated-invites.html) — do not re-derive or eyeball these numbers.
//
// Correction from the original prose spec: the reference has no static
// marigold dots sitting between the leaves. The only marigolds in the
// working prototype are the separately-animated Drift petals (a web-only,
// ambient background layer per the reference — not part of this static
// motif). Built to match the actual reference, not the earlier description.
//
// leafCount isn't exposed as a prop: the 9 leaf positions below were
// hand-placed along the string's curve in the reference, not generated by a
// formula — supporting an arbitrary count would mean inventing new
// positions, which is exactly what "copy directly, don't re-derive" rules
// out. Always renders all 9.

const LEAF_POSITIONS = [
  { x: 34, y: 56 },
  { x: 74, y: 72 },
  { x: 114, y: 86 },
  { x: 154, y: 95 },
  { x: 198, y: 99 },
  { x: 242, y: 95 },
  { x: 282, y: 86 },
  { x: 322, y: 72 },
  { x: 362, y: 56 },
];
const LEAF_PATH = 'c7 9 7 22 0 32-7-10-7-23 0-32z';

export default function TornArch({ width = 400, height = 140, color = '#D4A03C' }) {
  return (
    <Svg width={width} height={height} viewBox="0 0 400 140" fill="none">
      <Path
        d="M14 44 Q200 118 386 44"
        stroke={color}
        strokeWidth={1.6}
        fill="none"
        opacity={0.85}
      />
      {LEAF_POSITIONS.map((pos, i) => (
        <Path key={i} d={`M${pos.x} ${pos.y}${LEAF_PATH}`} fill={color} />
      ))}
    </Svg>
  );
}
