-- Event-driven vendor requirement system — Phase 1: schema + seed data.
-- No hardcoded event logic anywhere else in the app should ever need to
-- branch on event type; every event type/sub-event/requirement lives here,
-- so adding a new one is an INSERT, never a code change.

create table public.event_types (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  icon text,
  has_sub_events boolean default false,
  sort_order int4 default 0
);

create table public.sub_events (
  id uuid primary key default gen_random_uuid(),
  event_type_id uuid references public.event_types(id) on delete cascade,
  slug text not null,
  name text not null,
  typical_day_offset int4,
  sort_order int4 default 0,
  unique(event_type_id, slug)
);

-- event_requirements — REWRITTEN 2026-08-16 to match the live table's real
-- shape. This table's schema was changed directly against the live database
-- (via the Supabase SQL editor) at some point after this file was first
-- written, and that change was never captured back into this file — a
-- 28-migration-file audit on 2026-08-16 caught the drift: the create table
-- below used to declare event_type_id/sub_event_id (uuid FKs into
-- event_types/sub_events), category, and contextual_hint. None of those
-- exist on the live table today. Preserved here for anyone wondering
-- "didn't this used to reference event_types/sub_events by FK":
--
--   create table public.event_requirements (
--     id uuid primary key default gen_random_uuid(),
--     event_type_id uuid references public.event_types(id) on delete cascade,
--     sub_event_id uuid references public.sub_events(id) on delete cascade,
--     category text not null,
--     priority text not null check (priority in ('essential','recommended','optional')),
--     contextual_label text,
--     contextual_hint text,
--     min_guest_count int4,
--     max_guest_count int4,
--     min_age int4,
--     max_age int4,
--     sort_order int4 default 0
--   );
--
-- The live table instead addresses event types/sub-events by slug directly
-- (text, no FK) rather than by uuid join, renamed category -> category_slug
-- (a real vendor_categories slug) with a separate item_name column, dropped
-- contextual_hint, added condition_flag/suppressed_when_dry/
-- suppressed_when_veg, and changed the priority values from
-- essential/recommended/optional to a five-tier P1-P5 scale. The version
-- below is the real, current, live definition.
create table public.event_requirements (
  id uuid primary key default gen_random_uuid(),
  event_type_slug text not null,
  sub_event_slug text,
  item_name text not null,
  category_slug text not null,
  priority text not null check (priority in ('P1','P2','P3','P4','P5')),
  contextual_label text,
  min_guest_count int4,
  max_guest_count int4,
  min_age int4,
  max_age int4,
  condition_flag text,
  suppressed_when_dry boolean default false,
  suppressed_when_veg boolean default false,
  sort_order int4 default 0
);

create table public.category_interest (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  event_id uuid references public.events(id) on delete set null,
  category text not null,
  city text,
  event_type_slug text,
  notified boolean default false,
  created_at timestamp with time zone default now(),
  unique(user_id, category, event_id)
);

alter table public.event_types enable row level security;
alter table public.sub_events enable row level security;
alter table public.event_requirements enable row level security;
alter table public.category_interest enable row level security;

create policy "Anyone can read event types"
  on public.event_types for select using (true);
create policy "Anyone can read sub events"
  on public.sub_events for select using (true);
create policy "Anyone can read requirements"
  on public.event_requirements for select using (true);
create policy "Users manage own interest"
  on public.category_interest for all using (user_id = auth.uid());

create index idx_req_event on public.event_requirements(event_type_slug);
create index idx_req_sub on public.event_requirements(sub_event_slug);
create index idx_sub_events_type on public.sub_events(event_type_id);
create index idx_interest_category on public.category_interest(category, city);

-- Sub-events are tags on bookings, not separate event rows — one events row
-- per wedding, bookings carry an optional sub_event_id.
alter table public.events
add column if not exists event_type_slug text,
add column if not exists guest_count int4,
add column if not exists child_age int4,
add column if not exists budget_total int4;

alter table public.bookings
add column if not exists sub_event_id uuid references public.sub_events(id) on delete set null;

-- Categories the host marked as sorted offline — no vendor booking needed,
-- but still counts as "handled" for checklist purposes.
alter table public.events
add column if not exists arranged_categories text[] default '{}';


-- ─────────────────────────────────────────────────────────────────────────
-- Seed data — idempotent. event_types/sub_events use real unique
-- constraints (on conflict do nothing).
-- ─────────────────────────────────────────────────────────────────────────

insert into event_types (slug, name, icon, has_sub_events, sort_order) values
  ('hindu-wedding', 'Hindu Wedding', '💍', true, 0),
  ('engagement', 'Engagement', '💑', false, 1),
  ('kids-birthday', 'Kids'' Birthday', '🎈', false, 2),
  ('adult-birthday', 'Birthday', '🎂', false, 3),
  ('griha-pravesh', 'Griha Pravesh', '🏡', false, 4),
  ('satyanarayan-katha', 'Satyanarayan Katha', '🙏', false, 5),
  ('mundan', 'Mundan', '👶', false, 6),
  ('godh-bharai', 'Godh Bharai', '🤰', false, 7),
  ('anniversary', 'Anniversary', '❤️', false, 8),
  ('corporate-event', 'Corporate Event', '💼', false, 9)
on conflict (slug) do nothing;

insert into sub_events (event_type_id, slug, name, typical_day_offset, sort_order)
select et.id, v.slug, v.name, v.typical_day_offset, v.sort_order
from (values
  ('roka', 'Roka', -60, 0),
  ('mehendi', 'Mehendi', -2, 1),
  ('haldi', 'Haldi', -1, 2),
  ('sangeet', 'Sangeet', -1, 3),
  ('baraat', 'Baraat', 0, 4),
  ('pheras', 'Pheras', 0, 5),
  ('reception', 'Reception', 1, 6)
) as v(slug, name, typical_day_offset, sort_order)
cross join (select id from event_types where slug = 'hindu-wedding') et
on conflict (event_type_id, slug) do nothing;

-- event_requirements seed — REWRITTEN 2026-08-16 to match the live table's
-- real content (370 rows across 16 event types / 54 category slugs,
-- confirmed live via `select count(*), count(distinct event_type_slug),
-- count(distinct category_slug) from event_requirements`). This is a much
-- larger, differently-shaped dataset than the ~110-row/10-event-type seed
-- this file originally shipped with — it reflects the taxonomy alignment
-- and P1-P5 priority-tier work done directly against the live table after
-- this file was last edited. No `delete + insert` scoping this time (unlike
-- the original file): the table has no natural unique key, and re-running
-- this insert against a table that already has this exact data would create
-- duplicates, not idempotently no-op — this block is a record of current
-- live content, not something meant to be re-run against a database that
-- already has it.
insert into event_requirements (
  event_type_slug, sub_event_slug, item_name, category_slug, priority, contextual_label,
  min_guest_count, max_guest_count, min_age, max_age, condition_flag,
  suppressed_when_dry, suppressed_when_veg, sort_order
) values
  ('adult-birthday', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('adult-birthday', null, 'Decor', 'decor', 'P1', null, null, null, null, null, null, false, false, 2),
  ('adult-birthday', null, 'Caterer', 'catering', 'P1', null, null, null, null, null, null, false, false, 3),
  ('adult-birthday', null, 'Cake', 'bakery-cakes', 'P1', null, null, null, null, null, null, false, false, 4),
  ('adult-birthday', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('adult-birthday', null, 'DJ', 'dj-music', 'P2', null, null, null, null, null, null, false, false, 11),
  ('adult-birthday', null, 'Bartender', 'bar-services', 'P2', null, null, null, null, null, null, true, false, 12),
  ('adult-birthday', null, 'Live music', 'live-bands', 'P3', null, null, null, null, null, null, false, false, 20),
  ('adult-birthday', null, 'Photo booth', 'photo-booths', 'P3', null, null, null, null, null, null, false, false, 21),
  ('adult-birthday', null, 'Lighting', 'lighting', 'P3', null, null, null, null, null, null, false, false, 22),
  ('adult-birthday', null, 'Celebrity DJ', 'celebrity-talent', 'P4', null, null, null, null, null, null, false, false, 30),
  ('adult-birthday', null, 'Valet parking', 'valet-parking', 'P5', null, 100, null, null, null, null, false, false, 40),
  ('adult-birthday', null, 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 41),
  ('anniversary', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('anniversary', null, 'Caterer', 'catering', 'P1', null, null, null, null, null, null, false, false, 2),
  ('anniversary', null, 'Cake', 'bakery-cakes', 'P1', null, null, null, null, null, null, false, false, 3),
  ('anniversary', null, 'Decor', 'decor', 'P1', null, null, null, null, null, null, false, false, 4),
  ('anniversary', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('anniversary', null, 'Live music', 'live-bands', 'P2', null, null, null, null, null, null, false, false, 11),
  ('anniversary', null, 'Floral decor', 'floral-decor', 'P3', null, null, null, null, null, null, false, false, 20),
  ('anniversary', null, 'Return gifts', 'return-gifts', 'P3', null, null, null, null, null, null, false, false, 21),
  ('anniversary', null, 'Photo booth', 'photo-booths', 'P3', null, null, null, null, null, null, false, false, 22),
  ('anniversary', null, 'Bar service', 'bar-services', 'P3', null, null, null, null, null, null, true, false, 23),
  ('anniversary', null, 'Luxury dining setup', 'furniture-seating', 'P4', null, null, null, null, null, null, false, false, 30),
  ('anniversary', null, 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 40),
  ('baby-shower', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('baby-shower', null, 'Decor', 'decor', 'P1', null, null, null, null, null, null, false, false, 2),
  ('baby-shower', null, 'Cake', 'bakery-cakes', 'P1', null, null, null, null, null, null, false, false, 3),
  ('baby-shower', null, 'Caterer', 'catering', 'P1', null, null, null, null, null, null, false, false, 4),
  ('baby-shower', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('baby-shower', null, 'Games host', 'kids-entertainment', 'P2', null, null, null, null, null, null, false, false, 11),
  ('baby-shower', null, 'Return gifts', 'return-gifts', 'P3', null, null, null, null, null, null, false, false, 20),
  ('baby-shower', null, 'Balloon artist', 'kids-entertainment', 'P3', null, null, null, null, null, null, false, false, 21),
  ('baby-shower', null, 'Floral decor', 'floral-decor', 'P3', null, null, null, null, null, null, false, false, 22),
  ('baby-shower', null, 'Luxury theme setup', 'decor', 'P4', null, null, null, null, null, null, false, false, 30),
  ('baby-shower', null, 'Babysitter', 'childcare', 'P5', null, null, null, null, null, 'has_children', false, false, 40),
  ('baby-shower', null, 'Housekeeping', 'housekeeping', 'P5', null, 100, null, null, null, null, false, false, 41),
  ('concert', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('concert', null, 'Stage', 'stage-trussing', 'P1', null, null, null, null, null, null, false, false, 2),
  ('concert', null, 'Sound system', 'sound-av', 'P1', null, null, null, null, null, null, false, false, 3),
  ('concert', null, 'Lighting', 'lighting', 'P1', null, null, null, null, null, null, false, false, 4),
  ('concert', null, 'Security', 'security', 'P1', null, null, null, null, null, null, false, false, 5),
  ('concert', null, 'Power backup', 'power-utilities', 'P1', null, null, null, null, null, null, false, false, 6),
  ('concert', null, 'Ticketing', 'ticketing', 'P2', null, null, null, null, null, null, false, false, 10),
  ('concert', null, 'Food vendors', 'live-food-stalls', 'P2', null, null, null, null, null, null, false, false, 11),
  ('concert', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 12),
  ('concert', null, 'LED screens', 'led-screens', 'P2', null, null, null, null, null, null, false, false, 13),
  ('concert', null, 'Barricading', 'stage-trussing', 'P2', null, null, null, null, null, null, false, false, 14),
  ('concert', null, 'Merchandise', 'return-gifts', 'P3', null, null, null, null, null, null, false, false, 20),
  ('concert', null, 'Bar service', 'bar-services', 'P3', null, null, null, null, null, null, true, false, 21),
  ('concert', null, 'Videographer', 'videography', 'P3', null, null, null, null, null, null, false, false, 22),
  ('concert', null, 'Drone coverage', 'drone-aerial', 'P4', null, null, null, null, null, null, false, false, 30),
  ('concert', null, 'Laser show', 'fireworks-effects', 'P4', null, null, null, null, null, null, false, false, 31),
  ('concert', null, 'VIP hospitality', 'hospitality-staff', 'P5', null, null, null, null, null, null, false, false, 40),
  ('concert', null, 'Medical team', 'medical-support', 'P5', null, 200, null, null, null, null, false, false, 41),
  ('concert', null, 'Housekeeping', 'housekeeping', 'P5', null, null, null, null, null, null, false, false, 42),
  ('corporate-conference', null, 'Venue', 'venues', 'P1', 'Conference venue', null, null, null, null, null, false, false, 1),
  ('corporate-conference', null, 'Registration desk', 'registration-guest-tech', 'P1', null, null, null, null, null, null, false, false, 2),
  ('corporate-conference', null, 'AV equipment', 'sound-av', 'P1', null, null, null, null, null, null, false, false, 3),
  ('corporate-conference', null, 'Projector', 'sound-av', 'P1', null, null, null, null, null, null, false, false, 4),
  ('corporate-conference', null, 'Sound system', 'sound-av', 'P1', null, null, null, null, null, null, false, false, 5),
  ('corporate-conference', null, 'LED screen', 'led-screens', 'P1', null, null, null, null, null, null, false, false, 6),
  ('corporate-conference', null, 'Seating', 'furniture-seating', 'P1', null, null, null, null, null, null, false, false, 7),
  ('corporate-conference', null, 'Catering', 'catering', 'P1', null, null, null, null, null, null, false, false, 8),
  ('corporate-conference', null, 'Branding', 'branding-print', 'P2', 'Standees and backdrop', null, null, null, null, null, false, false, 10),
  ('corporate-conference', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 11),
  ('corporate-conference', null, 'Videographer', 'videography', 'P2', null, null, null, null, null, null, false, false, 12),
  ('corporate-conference', null, 'Wi-Fi', 'connectivity', 'P2', null, null, null, null, null, null, false, false, 13),
  ('corporate-conference', null, 'Event app', 'registration-guest-tech', 'P2', null, 200, null, null, null, null, false, false, 14),
  ('corporate-conference', null, 'Live streaming', 'live-streaming', 'P3', null, null, null, null, null, null, false, false, 20),
  ('corporate-conference', null, 'Simultaneous translation', 'translation', 'P3', null, null, null, null, null, 'has_foreign_guests', false, false, 21),
  ('corporate-conference', null, 'Exhibition booths', 'booth-exhibition', 'P3', null, null, null, null, null, null, false, false, 22),
  ('corporate-conference', null, 'Coffee bar', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 23),
  ('corporate-conference', null, 'Emcee', 'anchors-emcees', 'P3', null, null, null, null, null, null, false, false, 24),
  ('corporate-conference', null, 'AI networking', 'interactive-tech', 'P4', null, null, null, null, null, null, false, false, 30),
  ('corporate-conference', null, 'RFID badges', 'registration-guest-tech', 'P4', null, 300, null, null, null, null, false, false, 31),
  ('corporate-conference', null, 'Interactive screens', 'interactive-tech', 'P4', null, null, null, null, null, null, false, false, 32),
  ('corporate-conference', null, 'VIP lounge', 'hospitality-staff', 'P5', null, null, null, null, null, null, false, false, 40),
  ('corporate-conference', null, 'Medical team', 'medical-support', 'P5', null, 300, null, null, null, null, false, false, 41),
  ('corporate-conference', null, 'Security', 'security', 'P5', null, 200, null, null, null, null, false, false, 42),
  ('corporate-conference', null, 'Valet parking', 'valet-parking', 'P5', null, 150, null, null, null, null, false, false, 43),
  ('corporate-conference', null, 'Housekeeping', 'housekeeping', 'P5', null, 100, null, null, null, null, false, false, 44),
  ('engagement', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('engagement', null, 'Decor', 'decor', 'P1', 'Ring ceremony stage', null, null, null, null, null, false, false, 2),
  ('engagement', null, 'Caterer', 'catering', 'P1', null, null, null, null, null, null, false, false, 3),
  ('engagement', null, 'Photographer', 'photography', 'P1', null, null, null, null, null, null, false, false, 4),
  ('engagement', null, 'Cake', 'bakery-cakes', 'P1', null, null, null, null, null, null, false, false, 5),
  ('engagement', null, 'Videographer', 'videography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('engagement', null, 'DJ', 'dj-music', 'P2', null, null, null, null, null, null, false, false, 11),
  ('engagement', null, 'Makeup artist', 'makeup-styling', 'P2', null, null, null, null, null, null, false, false, 12),
  ('engagement', null, 'Floral decor', 'floral-decor', 'P2', null, null, null, null, null, null, false, false, 13),
  ('engagement', null, 'Invitations', 'invitations', 'P2', null, null, null, null, null, null, false, false, 14),
  ('engagement', null, 'Live singer', 'live-bands', 'P3', null, null, null, null, null, null, false, false, 20),
  ('engagement', null, 'Photo booth', 'photo-booths', 'P3', null, null, null, null, null, null, false, false, 21),
  ('engagement', null, 'Return gifts', 'return-gifts', 'P3', null, null, null, null, null, null, false, false, 22),
  ('engagement', null, 'Anchor', 'anchors-emcees', 'P3', null, null, null, null, null, null, false, false, 23),
  ('engagement', null, 'Drone coverage', 'drone-aerial', 'P4', null, null, null, null, null, null, false, false, 30),
  ('engagement', null, 'LED stage', 'led-screens', 'P4', null, null, null, null, null, null, false, false, 31),
  ('engagement', null, 'Luxury entry', 'transportation', 'P4', null, null, null, null, null, null, false, false, 32),
  ('engagement', null, 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 40),
  ('engagement', null, 'Power backup', 'power-utilities', 'P5', null, null, null, null, null, null, false, false, 41),
  ('exhibition', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('exhibition', null, 'Booth builder', 'booth-exhibition', 'P1', null, null, null, null, null, null, false, false, 2),
  ('exhibition', null, 'Power supply', 'power-utilities', 'P1', null, null, null, null, null, null, false, false, 3),
  ('exhibition', null, 'Registration desk', 'registration-guest-tech', 'P1', null, null, null, null, null, null, false, false, 4),
  ('exhibition', null, 'Printing', 'branding-print', 'P2', null, null, null, null, null, null, false, false, 10),
  ('exhibition', null, 'Branding', 'branding-print', 'P2', null, null, null, null, null, null, false, false, 11),
  ('exhibition', null, 'Lighting', 'lighting', 'P2', null, null, null, null, null, null, false, false, 12),
  ('exhibition', null, 'Furniture', 'furniture-seating', 'P2', null, null, null, null, null, null, false, false, 13),
  ('exhibition', null, 'Photographer', 'photography', 'P3', null, null, null, null, null, null, false, false, 20),
  ('exhibition', null, 'Wi-Fi', 'connectivity', 'P3', null, null, null, null, null, null, false, false, 21),
  ('exhibition', null, 'Catering', 'catering', 'P3', null, null, null, null, null, null, false, false, 22),
  ('exhibition', null, 'Interactive displays', 'interactive-tech', 'P4', null, null, null, null, null, null, false, false, 30),
  ('exhibition', null, 'Medical team', 'medical-support', 'P5', null, 300, null, null, null, null, false, false, 40),
  ('exhibition', null, 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 41),
  ('exhibition', null, 'Housekeeping', 'housekeeping', 'P5', null, null, null, null, null, null, false, false, 42),
  ('festival-fair', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('festival-fair', null, 'Stage', 'stage-trussing', 'P1', null, null, null, null, null, null, false, false, 2),
  ('festival-fair', null, 'Security', 'security', 'P1', null, null, null, null, null, null, false, false, 3),
  ('festival-fair', null, 'Power backup', 'power-utilities', 'P1', null, null, null, null, null, null, false, false, 4),
  ('festival-fair', null, 'Sound system', 'sound-av', 'P1', null, null, null, null, null, null, false, false, 5),
  ('festival-fair', null, 'Food vendors', 'live-food-stalls', 'P2', null, null, null, null, null, null, false, false, 10),
  ('festival-fair', null, 'Performers', 'live-bands', 'P2', null, null, null, null, null, null, false, false, 11),
  ('festival-fair', null, 'Lighting', 'lighting', 'P2', null, null, null, null, null, null, false, false, 12),
  ('festival-fair', null, 'Tent and canopy', 'tent-mandap', 'P2', null, null, null, null, null, null, false, false, 13),
  ('festival-fair', null, 'Photographer', 'photography', 'P3', null, null, null, null, null, null, false, false, 20),
  ('festival-fair', null, 'Kids activities', 'kids-entertainment', 'P3', null, null, null, null, null, 'has_children', false, false, 21),
  ('festival-fair', null, 'Ticketing', 'ticketing', 'P3', null, null, null, null, null, null, false, false, 22),
  ('festival-fair', null, 'Laser show', 'fireworks-effects', 'P4', null, null, null, null, null, null, false, false, 30),
  ('festival-fair', null, 'VIP area', 'hospitality-staff', 'P5', null, null, null, null, null, null, false, false, 40),
  ('festival-fair', null, 'Medical team', 'medical-support', 'P5', null, 200, null, null, null, null, false, false, 41),
  ('festival-fair', null, 'Housekeeping', 'housekeeping', 'P5', null, null, null, null, null, null, false, false, 42),
  ('hindu-wedding', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('hindu-wedding', null, 'Caterer', 'catering', 'P1', null, null, null, null, null, null, false, false, 2),
  ('hindu-wedding', null, 'Decorator', 'decor', 'P1', 'Mandap and stage decoration', null, null, null, null, null, false, false, 3),
  ('hindu-wedding', null, 'Priest', 'priests-officiants', 'P1', 'Pandit', null, null, null, null, null, false, false, 4),
  ('hindu-wedding', null, 'Photographer', 'photography', 'P1', null, null, null, null, null, null, false, false, 5),
  ('hindu-wedding', null, 'Tent and mandap', 'tent-mandap', 'P1', null, null, null, null, null, null, false, false, 6),
  ('hindu-wedding', null, 'Basic sound', 'sound-av', 'P1', null, null, null, null, null, null, false, false, 7),
  ('hindu-wedding', null, 'Basic lighting', 'lighting', 'P1', null, null, null, null, null, null, false, false, 8),
  ('hindu-wedding', null, 'Bridal makeup', 'makeup-styling', 'P1', null, null, null, null, null, null, false, false, 9),
  ('hindu-wedding', null, 'Guest seating', 'furniture-seating', 'P1', null, null, null, null, null, null, false, false, 10),
  ('hindu-wedding', null, 'Power backup', 'power-utilities', 'P1', null, null, null, null, null, null, false, false, 11),
  ('hindu-wedding', null, 'Wedding planner', 'event-planning', 'P2', null, 150, null, null, null, null, false, false, 20),
  ('hindu-wedding', null, 'Videographer', 'videography', 'P2', null, null, null, null, null, null, false, false, 21),
  ('hindu-wedding', null, 'Floral decor', 'floral-decor', 'P2', null, null, null, null, null, null, false, false, 22),
  ('hindu-wedding', null, 'Mehendi artist', 'mehendi', 'P2', null, null, null, null, null, null, false, false, 23),
  ('hindu-wedding', null, 'DJ', 'dj-music', 'P2', null, null, null, null, null, null, false, false, 24),
  ('hindu-wedding', null, 'Transportation', 'transportation', 'P2', 'Bride and groom transport', null, null, null, null, null, false, false, 25),
  ('hindu-wedding', null, 'Guest accommodation', 'guest-accommodation', 'P2', null, null, null, null, null, 'has_outstation_guests', false, false, 26),
  ('hindu-wedding', null, 'Invitation cards', 'invitations', 'P2', null, null, null, null, null, null, false, false, 27),
  ('hindu-wedding', null, 'Hospitality team', 'hospitality-staff', 'P2', null, 150, null, null, null, null, false, false, 28),
  ('hindu-wedding', null, 'Wedding cake', 'bakery-cakes', 'P2', null, null, null, null, null, null, false, false, 29),
  ('hindu-wedding', null, 'Return gifts', 'return-gifts', 'P2', null, null, null, null, null, null, false, false, 30),
  ('hindu-wedding', null, 'Live band', 'live-bands', 'P3', null, null, null, null, null, null, false, false, 40),
  ('hindu-wedding', null, 'Choreographer', 'choreography', 'P3', null, null, null, null, null, null, false, false, 41),
  ('hindu-wedding', null, 'Anchor', 'anchors-emcees', 'P3', null, null, null, null, null, null, false, false, 42),
  ('hindu-wedding', null, 'Rain cover / weather tent', 'tent-mandap', 'P4', 'Monsoon-season backup', null, null, null, null, 'is_monsoon', false, false, 43),
  ('hindu-wedding', null, 'Photo booth', 'photo-booths', 'P3', null, null, null, null, null, null, false, false, 43),
  ('hindu-wedding', null, 'Live food stations', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 44),
  ('hindu-wedding', null, 'Extra cooling', 'power-utilities', 'P4', 'Fans / AC for summer-season guests', null, null, null, null, 'is_summer', false, false, 44),
  ('hindu-wedding', null, 'Mocktail bar', 'bar-services', 'P3', null, null, null, null, null, null, false, false, 45),
  ('hindu-wedding', null, 'Luxury furniture', 'furniture-seating', 'P3', null, null, null, null, null, null, false, false, 46),
  ('hindu-wedding', null, 'Valet parking', 'valet-parking', 'P3', null, 150, null, null, null, null, false, false, 47),
  ('hindu-wedding', null, 'Kids entertainment', 'kids-entertainment', 'P3', null, null, null, null, null, 'has_children', false, false, 48),
  ('hindu-wedding', null, 'Dhol players', 'dhol-baraat', 'P3', null, null, null, null, null, null, false, false, 49),
  ('hindu-wedding', null, 'Drone coverage', 'drone-aerial', 'P4', null, null, null, null, null, null, false, false, 60),
  ('hindu-wedding', null, 'Celebrity artist', 'celebrity-talent', 'P4', null, null, null, null, null, null, false, false, 61),
  ('hindu-wedding', null, 'Luxury cars', 'transportation', 'P4', null, null, null, null, null, null, false, false, 62),
  ('hindu-wedding', null, 'Vintage car', 'transportation', 'P4', null, null, null, null, null, null, false, false, 63),
  ('hindu-wedding', null, 'Fireworks', 'fireworks-effects', 'P4', null, null, null, null, null, null, false, false, 64),
  ('hindu-wedding', null, 'Ice sculpture', 'decor', 'P4', null, null, null, null, null, null, false, false, 65),
  ('hindu-wedding', null, 'LED dance floor', 'lighting', 'P4', null, null, null, null, null, null, false, false, 66),
  ('hindu-wedding', null, '360 booth', 'photo-booths', 'P4', null, null, null, null, null, null, false, false, 67),
  ('hindu-wedding', null, 'Wedding website', 'invitations', 'P4', null, null, null, null, null, null, false, false, 68),
  ('hindu-wedding', null, 'Ambulance on standby', 'medical-support', 'P5', null, 200, null, null, null, null, false, false, 80),
  ('hindu-wedding', null, 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 81),
  ('hindu-wedding', null, 'Weather backup', 'tent-mandap', 'P5', 'Marquee cover', null, null, null, null, 'is_outdoor', false, false, 82),
  ('hindu-wedding', null, 'Childcare', 'childcare', 'P5', null, null, null, null, null, 'has_children', false, false, 83),
  ('hindu-wedding', null, 'Pet care', 'pet-care', 'P5', null, null, null, null, null, 'has_pets', false, false, 84),
  ('hindu-wedding', null, 'Translator', 'translation', 'P5', null, null, null, null, null, 'has_foreign_guests', false, false, 85),
  ('hindu-wedding', null, 'Housekeeping', 'housekeeping', 'P5', null, 100, null, null, null, null, false, false, 86),
  ('hindu-wedding', 'baraat', 'Dhol players', 'dhol-baraat', 'P1', null, null, null, null, null, null, false, false, 1),
  ('hindu-wedding', 'baraat', 'Baraat transport', 'transportation', 'P2', 'Ghodi or vintage car', null, null, null, null, null, false, false, 10),
  ('hindu-wedding', 'baraat', 'Lighting', 'lighting', 'P2', null, null, null, null, null, null, false, false, 11),
  ('hindu-wedding', 'baraat', 'Photographer', 'photography', 'P3', null, null, null, null, null, null, false, false, 20),
  ('hindu-wedding', 'baraat', 'Fireworks', 'fireworks-effects', 'P4', null, null, null, null, null, null, false, false, 30),
  ('hindu-wedding', 'baraat', 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 40),
  ('hindu-wedding', 'haldi', 'Haldi decor', 'decor', 'P1', 'Marigold and haldi setup', null, null, null, null, null, false, false, 1),
  ('hindu-wedding', 'haldi', 'Caterer', 'catering', 'P1', null, null, null, null, null, null, false, false, 2),
  ('hindu-wedding', 'haldi', 'Photographer', 'photography', 'P1', null, null, null, null, null, null, false, false, 3),
  ('hindu-wedding', 'haldi', 'Floral decor', 'floral-decor', 'P2', null, null, null, null, null, null, false, false, 10),
  ('hindu-wedding', 'haldi', 'DJ', 'dj-music', 'P2', null, null, null, null, null, null, false, false, 11),
  ('hindu-wedding', 'haldi', 'Makeup artist', 'makeup-styling', 'P2', null, null, null, null, null, null, false, false, 12),
  ('hindu-wedding', 'haldi', 'Dhol players', 'dhol-baraat', 'P3', null, null, null, null, null, null, false, false, 20),
  ('hindu-wedding', 'haldi', 'Games host', 'kids-entertainment', 'P3', null, null, null, null, null, null, false, false, 21),
  ('hindu-wedding', 'haldi', 'Return gifts', 'return-gifts', 'P3', null, null, null, null, null, null, false, false, 22),
  ('hindu-wedding', 'haldi', 'Drone coverage', 'drone-aerial', 'P4', null, null, null, null, null, null, false, false, 30),
  ('hindu-wedding', 'haldi', 'Housekeeping', 'housekeeping', 'P5', null, null, null, null, null, null, false, false, 40),
  ('hindu-wedding', 'mehendi', 'Mehendi artist', 'mehendi', 'P1', null, null, null, null, null, null, false, false, 1),
  ('hindu-wedding', 'mehendi', 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 2),
  ('hindu-wedding', 'mehendi', 'Decor', 'decor', 'P1', 'Mehendi setup', null, null, null, null, null, false, false, 3),
  ('hindu-wedding', 'mehendi', 'Caterer', 'catering', 'P1', 'Snacks and chaat', null, null, null, null, null, false, false, 4),
  ('hindu-wedding', 'mehendi', 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('hindu-wedding', 'mehendi', 'DJ', 'dj-music', 'P2', null, null, null, null, null, null, false, false, 11),
  ('hindu-wedding', 'mehendi', 'Live music', 'live-bands', 'P2', null, null, null, null, null, null, false, false, 12),
  ('hindu-wedding', 'mehendi', 'Dessert counter', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 20),
  ('hindu-wedding', 'mehendi', 'Games host', 'kids-entertainment', 'P3', null, null, null, null, null, null, false, false, 21),
  ('hindu-wedding', 'mehendi', 'Return gifts', 'return-gifts', 'P3', null, null, null, null, null, null, false, false, 22),
  ('hindu-wedding', 'mehendi', 'Celebrity mehendi artist', 'celebrity-talent', 'P4', null, null, null, null, null, null, false, false, 30),
  ('hindu-wedding', 'mehendi', 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 40),
  ('hindu-wedding', 'pheras', 'Priest', 'priests-officiants', 'P1', 'Pandit', null, null, null, null, null, false, false, 1),
  ('hindu-wedding', 'pheras', 'Mandap decor', 'decor', 'P1', null, null, null, null, null, null, false, false, 2),
  ('hindu-wedding', 'pheras', 'Ritual supplies', 'ritual-supplies', 'P1', null, null, null, null, null, null, false, false, 3),
  ('hindu-wedding', 'pheras', 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('hindu-wedding', 'pheras', 'Videographer', 'videography', 'P2', null, null, null, null, null, null, false, false, 11),
  ('hindu-wedding', 'pheras', 'Floral decor', 'floral-decor', 'P2', null, null, null, null, null, null, false, false, 12),
  ('hindu-wedding', 'reception', 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('hindu-wedding', 'reception', 'Caterer', 'catering', 'P1', null, null, null, null, null, null, false, false, 2),
  ('hindu-wedding', 'reception', 'Reception stage', 'decor', 'P1', null, null, null, null, null, null, false, false, 3),
  ('hindu-wedding', 'reception', 'Photographer', 'photography', 'P1', null, null, null, null, null, null, false, false, 4),
  ('hindu-wedding', 'reception', 'DJ', 'dj-music', 'P2', null, null, null, null, null, null, false, false, 10),
  ('hindu-wedding', 'reception', 'Lighting', 'lighting', 'P2', null, null, null, null, null, null, false, false, 11),
  ('hindu-wedding', 'reception', 'Makeup artist', 'makeup-styling', 'P2', null, null, null, null, null, null, false, false, 12),
  ('hindu-wedding', 'reception', 'Videographer', 'videography', 'P2', null, null, null, null, null, null, false, false, 13),
  ('hindu-wedding', 'reception', 'Live band', 'live-bands', 'P3', null, null, null, null, null, null, false, false, 20),
  ('hindu-wedding', 'reception', 'Bar service', 'bar-services', 'P3', null, null, null, null, null, null, true, false, 21),
  ('hindu-wedding', 'reception', 'Live food stations', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 22),
  ('hindu-wedding', 'reception', 'Valet parking', 'valet-parking', 'P3', null, 150, null, null, null, null, false, false, 23),
  ('hindu-wedding', 'reception', 'Celebrity singer', 'celebrity-talent', 'P4', null, null, null, null, null, null, false, false, 30),
  ('hindu-wedding', 'reception', 'LED wall', 'led-screens', 'P4', null, null, null, null, null, null, false, false, 31),
  ('hindu-wedding', 'reception', 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 40),
  ('hindu-wedding', 'roka', 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('hindu-wedding', 'roka', 'Decor', 'decor', 'P1', null, null, null, null, null, null, false, false, 2),
  ('hindu-wedding', 'roka', 'Caterer', 'catering', 'P1', null, null, null, null, null, null, false, false, 3),
  ('hindu-wedding', 'roka', 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('hindu-wedding', 'roka', 'Priest', 'priests-officiants', 'P2', null, null, null, null, null, null, false, false, 11),
  ('hindu-wedding', 'roka', 'Sweet counter', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 20),
  ('hindu-wedding', 'sangeet', 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('hindu-wedding', 'sangeet', 'Stage', 'stage-trussing', 'P1', null, null, null, null, null, null, false, false, 2),
  ('hindu-wedding', 'sangeet', 'DJ', 'dj-music', 'P1', null, null, null, null, null, null, false, false, 3),
  ('hindu-wedding', 'sangeet', 'Sound system', 'sound-av', 'P1', null, null, null, null, null, null, false, false, 4),
  ('hindu-wedding', 'sangeet', 'Lighting', 'lighting', 'P1', null, null, null, null, null, null, false, false, 5),
  ('hindu-wedding', 'sangeet', 'Photographer', 'photography', 'P1', null, null, null, null, null, null, false, false, 6),
  ('hindu-wedding', 'sangeet', 'Videographer', 'videography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('hindu-wedding', 'sangeet', 'Choreographer', 'choreography', 'P2', null, null, null, null, null, null, false, false, 11),
  ('hindu-wedding', 'sangeet', 'Caterer', 'catering', 'P2', null, null, null, null, null, null, false, false, 12),
  ('hindu-wedding', 'sangeet', 'Anchor', 'anchors-emcees', 'P3', null, null, null, null, null, null, false, false, 20),
  ('hindu-wedding', 'sangeet', 'Live band', 'live-bands', 'P3', null, null, null, null, null, null, false, false, 21),
  ('hindu-wedding', 'sangeet', 'LED wall', 'led-screens', 'P3', null, null, null, null, null, null, false, false, 22),
  ('hindu-wedding', 'sangeet', 'Bar service', 'bar-services', 'P3', null, null, null, null, null, null, true, false, 23),
  ('hindu-wedding', 'sangeet', 'Celebrity performance', 'celebrity-talent', 'P4', null, null, null, null, null, null, false, false, 30),
  ('hindu-wedding', 'sangeet', 'Medical team', 'medical-support', 'P5', null, 200, null, null, null, null, false, false, 40),
  ('housewarming', null, 'Priest', 'priests-officiants', 'P1', null, null, null, null, null, null, false, false, 1),
  ('housewarming', null, 'Ritual supplies', 'ritual-supplies', 'P1', 'Havan samagri', null, null, null, null, null, false, false, 2),
  ('housewarming', null, 'Decor', 'decor', 'P1', 'Entrance toran and rangoli', null, null, null, null, null, false, false, 3),
  ('housewarming', null, 'Prasad caterer', 'prasad-caterer', 'P1', null, null, null, null, null, null, false, false, 4),
  ('housewarming', null, 'Caterer', 'catering', 'P2', null, null, null, null, null, null, false, false, 10),
  ('housewarming', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 11),
  ('housewarming', null, 'Floral decor', 'floral-decor', 'P2', null, null, null, null, null, null, false, false, 12),
  ('housewarming', null, 'Sweet counter', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 20),
  ('housewarming', null, 'Sound system', 'sound-av', 'P3', null, null, null, null, null, null, false, false, 21),
  ('housewarming', null, 'Return gifts', 'return-gifts', 'P3', 'Prasad distribution', null, null, null, null, null, false, false, 22),
  ('housewarming', null, 'Luxury floral decor', 'floral-decor', 'P4', null, null, null, null, null, null, false, false, 30),
  ('housewarming', null, 'Power backup', 'power-utilities', 'P5', null, null, null, null, null, null, false, false, 40),
  ('housewarming', null, 'Housekeeping', 'housekeeping', 'P5', null, null, null, null, null, null, false, false, 41),
  ('kids-birthday', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('kids-birthday', null, 'Balloon decor', 'decor', 'P1', 'Theme decoration and balloons', null, null, null, null, null, false, false, 2),
  ('kids-birthday', null, 'Cake', 'bakery-cakes', 'P1', null, null, null, null, null, null, false, false, 3),
  ('kids-birthday', null, 'Caterer', 'catering', 'P1', 'Kids snacks', null, null, null, null, null, false, false, 4),
  ('kids-birthday', null, 'Event coordinator', 'event-planning', 'P2', null, 75, null, null, null, null, false, false, 10),
  ('kids-birthday', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 11),
  ('kids-birthday', null, 'Magician', 'magician', 'P2', null, null, null, 4, 12, null, false, false, 12),
  ('kids-birthday', null, 'Mascot character', 'kids-entertainment', 'P2', null, null, null, null, 10, null, false, false, 13),
  ('kids-birthday', null, 'Games host', 'kids-entertainment', 'P2', null, null, null, 4, null, null, false, false, 14),
  ('kids-birthday', null, 'Return gifts', 'return-gifts', 'P2', null, null, null, null, null, null, false, false, 15),
  ('kids-birthday', null, 'Digital invitation', 'invitations', 'P2', null, null, null, null, null, null, false, false, 16),
  ('kids-birthday', null, 'Sound system', 'sound-av', 'P2', null, null, null, null, null, null, false, false, 17),
  ('kids-birthday', null, 'Face painting', 'kids-entertainment', 'P3', null, null, null, 3, 12, null, false, false, 20),
  ('kids-birthday', null, 'Tattoo artist', 'kids-entertainment', 'P3', null, null, null, 6, null, null, false, false, 21),
  ('kids-birthday', null, 'Bubble show', 'kids-entertainment', 'P3', null, null, null, null, 8, null, false, false, 22),
  ('kids-birthday', null, 'Puppet show', 'kids-entertainment', 'P3', null, null, null, null, 8, null, false, false, 23),
  ('kids-birthday', null, 'Balloon twister', 'kids-entertainment', 'P3', null, null, null, null, 10, null, false, false, 24),
  ('kids-birthday', null, 'Live cartoon artist', 'kids-entertainment', 'P3', null, null, null, 4, null, null, false, false, 25),
  ('kids-birthday', null, 'Science show', 'kids-entertainment', 'P3', null, null, null, 7, null, null, false, false, 26),
  ('kids-birthday', null, 'Cotton candy stall', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 27),
  ('kids-birthday', null, 'Popcorn machine', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 28),
  ('kids-birthday', null, 'Ice cream cart', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 29),
  ('kids-birthday', null, 'Gaming van', 'interactive-tech', 'P4', null, null, null, 8, null, null, false, false, 40),
  ('kids-birthday', null, 'VR zone', 'interactive-tech', 'P4', null, null, null, 8, null, null, false, false, 41),
  ('kids-birthday', null, '360 booth', 'photo-booths', 'P4', null, null, null, null, null, null, false, false, 42),
  ('kids-birthday', null, 'Bouncy castle', 'kids-entertainment', 'P4', null, null, null, null, 10, null, false, false, 43),
  ('kids-birthday', null, 'Luxury dessert table', 'live-food-stalls', 'P4', null, null, null, null, null, null, false, false, 44),
  ('kids-birthday', null, 'Babysitter', 'childcare', 'P5', null, null, null, null, 6, null, false, false, 50),
  ('kids-birthday', null, 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 51),
  ('kids-birthday', null, 'Power backup', 'power-utilities', 'P5', null, null, null, null, null, null, false, false, 52),
  ('kids-birthday', null, 'Housekeeping', 'housekeeping', 'P5', null, 100, null, null, null, null, false, false, 53),
  ('mundan', null, 'Priest', 'priests-officiants', 'P1', null, null, null, null, null, null, false, false, 1),
  ('mundan', null, 'Barber', 'barber-services', 'P1', 'Nai for mundan', null, null, null, null, null, false, false, 2),
  ('mundan', null, 'Prasad caterer', 'prasad-caterer', 'P1', null, null, null, null, null, null, false, false, 3),
  ('mundan', null, 'Ritual supplies', 'ritual-supplies', 'P1', null, null, null, null, null, null, false, false, 4),
  ('mundan', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('mundan', null, 'Decor', 'decor', 'P2', null, null, null, null, null, null, false, false, 11),
  ('mundan', null, 'Return gifts', 'return-gifts', 'P3', 'Prasad distribution', null, null, null, null, null, false, false, 20),
  ('mundan', null, 'Housekeeping', 'housekeeping', 'P5', null, 100, null, null, null, null, false, false, 40),
  ('naming-ceremony', null, 'Priest', 'priests-officiants', 'P1', null, null, null, null, null, null, false, false, 1),
  ('naming-ceremony', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 2),
  ('naming-ceremony', null, 'Decor', 'decor', 'P1', null, null, null, null, null, null, false, false, 3),
  ('naming-ceremony', null, 'Prasad caterer', 'prasad-caterer', 'P1', null, null, null, null, null, null, false, false, 4),
  ('naming-ceremony', null, 'Ritual supplies', 'ritual-supplies', 'P1', null, null, null, null, null, null, false, false, 5),
  ('naming-ceremony', null, 'Caterer', 'catering', 'P2', null, null, null, null, null, null, false, false, 10),
  ('naming-ceremony', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 11),
  ('naming-ceremony', null, 'Return gifts', 'return-gifts', 'P3', 'Prasad distribution', null, null, null, null, null, false, false, 20),
  ('naming-ceremony', null, 'Floral decor', 'floral-decor', 'P3', null, null, null, null, null, null, false, false, 21),
  ('naming-ceremony', null, 'Luxury decoration', 'decor', 'P4', null, null, null, null, null, null, false, false, 30),
  ('naming-ceremony', null, 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 40),
  ('product-launch', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('product-launch', null, 'Stage', 'stage-trussing', 'P1', null, null, null, null, null, null, false, false, 2),
  ('product-launch', null, 'LED wall', 'led-screens', 'P1', null, null, null, null, null, null, false, false, 3),
  ('product-launch', null, 'Branding', 'branding-print', 'P1', null, null, null, null, null, null, false, false, 4),
  ('product-launch', null, 'Sound and AV', 'sound-av', 'P1', null, null, null, null, null, null, false, false, 5),
  ('product-launch', null, 'Lighting', 'lighting', 'P1', null, null, null, null, null, null, false, false, 6),
  ('product-launch', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('product-launch', null, 'Videographer', 'videography', 'P2', null, null, null, null, null, null, false, false, 11),
  ('product-launch', null, 'Anchor', 'anchors-emcees', 'P2', null, null, null, null, null, null, false, false, 12),
  ('product-launch', null, 'Catering', 'catering', 'P2', null, null, null, null, null, null, false, false, 13),
  ('product-launch', null, 'Registration desk', 'registration-guest-tech', 'P2', null, 100, null, null, null, null, false, false, 14),
  ('product-launch', null, 'Influencers', 'pr-influencers', 'P3', null, null, null, null, null, null, false, false, 20),
  ('product-launch', null, 'PR agency', 'pr-influencers', 'P3', null, null, null, null, null, null, false, false, 21),
  ('product-launch', null, 'Live streaming', 'live-streaming', 'P3', null, null, null, null, null, null, false, false, 22),
  ('product-launch', null, 'Bar service', 'bar-services', 'P3', null, null, null, null, null, null, true, false, 23),
  ('product-launch', null, 'Celebrity guest', 'celebrity-talent', 'P4', null, null, null, null, null, null, false, false, 30),
  ('product-launch', null, 'Interactive displays', 'interactive-tech', 'P4', null, null, null, null, null, null, false, false, 31),
  ('product-launch', null, 'Security', 'security', 'P5', null, 150, null, null, null, null, false, false, 40),
  ('product-launch', null, 'Power backup', 'power-utilities', 'P5', null, null, null, null, null, null, false, false, 41),
  ('religious-event', null, 'Priest', 'priests-officiants', 'P1', null, null, null, null, null, null, false, false, 1),
  ('religious-event', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 2),
  ('religious-event', null, 'Seating', 'furniture-seating', 'P1', null, null, null, null, null, null, false, false, 3),
  ('religious-event', null, 'Prasad caterer', 'prasad-caterer', 'P1', null, null, null, null, null, null, false, false, 4),
  ('religious-event', null, 'Ritual supplies', 'ritual-supplies', 'P1', 'Havan samagri and puja items', null, null, null, null, null, false, false, 5),
  ('religious-event', null, 'Decor', 'decor', 'P2', null, null, null, null, null, null, false, false, 10),
  ('religious-event', null, 'Sound system', 'sound-av', 'P2', null, null, null, null, null, null, false, false, 11),
  ('religious-event', null, 'Floral decor', 'floral-decor', 'P2', 'Flowers and mala', null, null, null, null, null, false, false, 12),
  ('religious-event', null, 'Caterer', 'catering', 'P2', 'Brahmin bhoj', 50, null, null, null, null, false, false, 13),
  ('religious-event', null, 'Photographer', 'photography', 'P3', null, null, null, null, null, null, false, false, 20),
  ('religious-event', null, 'Bhajan mandali', 'live-bands', 'P3', null, null, null, null, null, null, false, false, 21),
  ('religious-event', null, 'Tent and mandap', 'tent-mandap', 'P3', null, null, null, null, null, null, false, false, 22),
  ('religious-event', null, 'Return gifts', 'return-gifts', 'P3', 'Prasad distribution', null, null, null, null, null, false, false, 23),
  ('religious-event', null, 'Live streaming', 'live-streaming', 'P4', null, null, null, null, null, null, false, false, 30),
  ('religious-event', null, 'Medical team', 'medical-support', 'P5', null, 200, null, null, null, null, false, false, 40),
  ('religious-event', null, 'Housekeeping', 'housekeeping', 'P5', null, 100, null, null, null, null, false, false, 41),
  ('religious-event', null, 'Power backup', 'power-utilities', 'P5', null, null, null, null, null, null, false, false, 42),
  ('sports-event', null, 'Venue', 'venues', 'P1', null, null, null, null, null, null, false, false, 1),
  ('sports-event', null, 'Registration desk', 'registration-guest-tech', 'P1', null, null, null, null, null, null, false, false, 2),
  ('sports-event', null, 'Medical team', 'medical-support', 'P1', null, null, null, null, null, null, false, false, 3),
  ('sports-event', null, 'Security', 'security', 'P1', null, null, null, null, null, null, false, false, 4),
  ('sports-event', null, 'Water stations', 'catering', 'P1', null, null, null, null, null, null, false, false, 5),
  ('sports-event', null, 'Photographer', 'photography', 'P2', null, null, null, null, null, null, false, false, 10),
  ('sports-event', null, 'Sound system', 'sound-av', 'P2', null, null, null, null, null, null, false, false, 11),
  ('sports-event', null, 'Branding', 'branding-print', 'P2', null, null, null, null, null, null, false, false, 12),
  ('sports-event', null, 'Timing and scoring', 'registration-guest-tech', 'P2', null, null, null, null, null, null, false, false, 13),
  ('sports-event', null, 'DJ', 'dj-music', 'P3', null, null, null, null, null, null, false, false, 20),
  ('sports-event', null, 'Stage', 'stage-trussing', 'P3', null, null, null, null, null, null, false, false, 21),
  ('sports-event', null, 'Food vendors', 'live-food-stalls', 'P3', null, null, null, null, null, null, false, false, 22),
  ('sports-event', null, 'Merchandise', 'return-gifts', 'P3', null, null, null, null, null, null, false, false, 23),
  ('sports-event', null, 'Drone coverage', 'drone-aerial', 'P4', null, null, null, null, null, null, false, false, 30),
  ('sports-event', null, 'Live streaming', 'live-streaming', 'P4', null, null, null, null, null, null, false, false, 31),
  ('sports-event', null, 'VIP hospitality', 'hospitality-staff', 'P5', null, null, null, null, null, null, false, false, 40),
  ('sports-event', null, 'Housekeeping', 'housekeeping', 'P5', null, null, null, null, null, null, false, false, 41),
  ('sports-event', null, 'Power backup', 'power-utilities', 'P5', null, null, null, null, null, null, false, false, 42);
-- TOTAL ROWS: 370 — matches live `select count(*) from event_requirements`
-- confirmed 2026-08-16.
